# ============================================
# 🔐 STEGO-ANALYZER
# Advanced Digital Forensics Suite
# ============================================

import tkinter as tk

from tkinter import (
    filedialog,
    messagebox,
    ttk
)

import io
import sys
import threading
import os

from datetime import datetime

# ============================================
# FORENSIC ENGINE
# ============================================

from universal_extractor import (
    analyze_file
)

# ============================================
# PDF REPORT LIBRARIES
# ============================================

from reportlab.platypus import (

    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle

)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import colors

# ============================================
# OUTPUT DIRECTORY
# ============================================

OUTPUT_DIR = "output"

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

# ============================================
# GLOBAL VARIABLES
# ============================================

last_results = ""

last_file = ""

scan_count = 0

# ============================================
# PDF REPORT GENERATOR
# ============================================

def generate_pdf_report(
    file_path,
    results
):

    timestamp = datetime.now().strftime(
        "%Y-%m-%d_%H-%M-%S"
    )

    pdf_path = (
        f"{OUTPUT_DIR}/"
        f"forensic_report_{timestamp}.pdf"
    )

    # ============================================
    # CREATE PDF
    # ============================================

    doc = SimpleDocTemplate(

        pdf_path,

        rightMargin=40,
        leftMargin=40,

        topMargin=40,
        bottomMargin=28

    )

    styles = getSampleStyleSheet()

    elements = []

    # ============================================
    # TITLE
    # ============================================

    title = Paragraph(
        """
        <font size=24>
        <b>STEGO-ANALYZER</b>
        </font>
        """,
        styles['Title']
    )

    elements.append(title)

    elements.append(
        Spacer(1, 20)
    )

    # ============================================
    # RISK LEVEL
    # ============================================

    risk = "LOW"

    color = "green"

    if "HIGHLY SUSPICIOUS" in results:

        risk = "HIGH"

        color = "red"

    elif "POSSIBLY SUSPICIOUS" in results:

        risk = "MEDIUM"

        color = "orange"

    summary = Paragraph(
        f"""
        <font size=12>

        <b>Risk Level:</b>

        <font color='{color}'>
        <b>{risk}</b>
        </font>

        </font>
        """,
        styles['BodyText']
    )

    elements.append(summary)

    elements.append(
        Spacer(1, 20)
    )

    # ============================================
    # FILE INFO
    # ============================================

    try:

        size = os.path.getsize(
            file_path
        )

    except:

        size = "Unknown"

    info_data = [

        ["Scanned File", file_path],

        ["Generated", timestamp],

        ["File Size", str(size)],

        ["Engine", "STEGO-ANALYZER"]

    ]

    table = Table(

        info_data,

        colWidths=[180, 380]

    )

    table.setStyle(TableStyle([

        ('BACKGROUND',
         (0, 0),
         (-1, 0),
         colors.darkblue),

        ('TEXTCOLOR',
         (0, 0),
         (-1, 0),
         colors.white),

        ('GRID',
         (0, 0),
         (-1, -1),
         1,
         colors.black),

        ('BACKGROUND',
         (0, 1),
         (-1, -1),
         colors.beige)

    ]))

    elements.append(table)

    elements.append(
        Spacer(1, 25)
    )

    # ============================================
    # RESULTS
    # ============================================

    heading = Paragraph(
        "<b>Detailed Analysis Results</b>",
        styles['Heading2']
    )

    elements.append(heading)

    result_para = Paragraph(
        f"""
        <font face='Courier' size=8>
        {results.replace(chr(10), '<br/>')}
        </font>
        """,
        styles['BodyText']
    )

    elements.append(result_para)

    elements.append(
        Spacer(1, 20)
    )

    # ============================================
    # FOOTER
    # ============================================

    footer = Paragraph(
        """
        <font size=9 color='grey'>
        Generated by STEGO-ANALYZER
        </font>
        """,
        styles['BodyText']
    )

    elements.append(footer)

    # ============================================
    # BUILD PDF
    # ============================================

    doc.build(elements)

    return pdf_path

# ============================================
# DISPLAY RESULTS
# ============================================

def display_results(results):

    lines = results.splitlines()

    for line in lines:

        if "🚨" in line:

            output.insert(
                tk.END,
                line + "\n",
                "danger"
            )

        elif "⚠" in line:

            output.insert(
                tk.END,
                line + "\n",
                "warning"
            )

        elif "✅" in line:

            output.insert(
                tk.END,
                line + "\n",
                "success"
            )

        else:

            output.insert(
                tk.END,
                line + "\n",
                "normal"
            )

    output.see(tk.END)

# ============================================
# UPDATE OUTPUT
# ============================================

def update_output(text):

    timestamp = datetime.now().strftime(
        "%H:%M:%S"
    )

    output.insert(

        tk.END,

        f"[{timestamp}] {text}",

        "normal"

    )

    output.see(tk.END)

    root.update_idletasks()

# ============================================
# RUN ANALYSIS
# ============================================

def run_analysis(file_path):

    global last_results
    global last_file
    global scan_count

    progress.start()

    status_label.config(
        text="Status: Scanning..."
    )

    captured_output = io.StringIO()

    sys.stdout = captured_output

    try:

        analyze_file(file_path)

    except Exception as e:

        print("[ERROR]", e)

    finally:

        sys.stdout = sys.__stdout__

    results = captured_output.getvalue()

    timestamp = datetime.now().strftime(
        "%H:%M:%S"
    )

    results += (
        f"\n\n✅ Scan Finished "
        f"at {timestamp}\n"
    )

    last_results = results

    last_file = file_path

    scan_count += 1

    # ============================================
    # UPDATE STATS
    # ============================================

    scan_counter_label.config(
        text=f"Scans: {scan_count}"
    )

    file_label.config(
        text=(
            f"File: "
            f"{os.path.basename(file_path)}"
        )
    )

    # ============================================
    # RISK STATUS
    # ============================================

    if "HIGHLY SUSPICIOUS" in results:

        risk_label.config(
            text="Risk: HIGH",
            fg="red"
        )

    elif "POSSIBLY SUSPICIOUS" in results:

        risk_label.config(
            text="Risk: MEDIUM",
            fg="orange"
        )

    else:

        risk_label.config(
            text="Risk: LOW",
            fg="lime"
        )

    # ============================================
    # DISPLAY RESULTS
    # ============================================

    output.after(

        0,

        lambda: display_results(results)

    )

    progress.stop()

    status_label.config(
        text=(
            f"Status: Scan Completed | "
            f"Total Scans: {scan_count}"
        )
    )

# ============================================
# SCAN FILE
# ============================================

def scan_file():

    file_path = filedialog.askopenfilename()

    if not file_path:
        return

    output.delete(
        1.0,
        tk.END
    )

    update_output(
        f"\n🔍 Scanning File:\n"
        f"{file_path}\n\n"
    )

    thread = threading.Thread(

        target=run_analysis,

        args=(file_path,)

    )

    thread.daemon = True

    thread.start()

# ============================================
# SCAN FOLDER
# ============================================

def scan_folder():

    folder_path = filedialog.askdirectory()

    if not folder_path:
        return

    output.delete(
        1.0,
        tk.END
    )

    update_output(
        f"\n📁 Folder Scan Started:\n"
        f"{folder_path}\n\n"
    )

    def worker():

        for root_dir, _, files in os.walk(folder_path):

            for file in files:

                path = os.path.join(
                    root_dir,
                    file
                )

                update_output(
                    f"\n====================\n"
                    f"{path}\n"
                    f"====================\n"
                )

                run_analysis(path)

        status_label.config(
            text="Status: Folder Scan Completed"
        )

    thread = threading.Thread(
        target=worker
    )

    thread.daemon = True

    thread.start()

# ============================================
# SAVE PDF
# ============================================

def save_pdf():

    global last_results
    global last_file

    if not last_results:

        messagebox.showwarning(

            "No Results",

            "Please scan a file first."

        )

        return

    try:

        pdf_path = generate_pdf_report(

            last_file,

            last_results

        )

        update_output(
            f"\n📄 PDF Saved:\n"
            f"{pdf_path}\n"
        )

        messagebox.showinfo(

            "Saved",

            f"PDF Report Saved:\n"
            f"{pdf_path}"

        )

    except Exception as e:

        messagebox.showerror(
            "Error",
            str(e)
        )

# ============================================
# CLEAR OUTPUT
# ============================================

def clear_output():

    output.delete(
        1.0,
        tk.END
    )

# ============================================
# MAIN WINDOW
# ============================================

root = tk.Tk()

root.title(
    "🔐 STEGO-ANALYZER"
)

root.geometry("1350x850")

root.configure(
    bg="#101010"
)

# ============================================
# TITLE
# ============================================

title = tk.Label(

    root,

    text="🔐 STEGO-ANALYZER",

    font=(
        "Arial",
        24,
        "bold"
    ),

    fg="#00FF99",

    bg="#101010"

)

title.pack(
    pady=10
)

# ============================================
# STATS FRAME
# ============================================

stats_frame = tk.Frame(
    root,
    bg="#151515"
)

stats_frame.pack(
    fill="x",
    padx=10,
    pady=5
)

scan_counter_label = tk.Label(

    stats_frame,

    text="Scans: 0",

    font=("Arial", 11, "bold"),

    bg="#151515",

    fg="cyan"

)

scan_counter_label.pack(
    side="left",
    padx=20
)

risk_label = tk.Label(

    stats_frame,

    text="Risk: LOW",

    font=("Arial", 11, "bold"),

    bg="#151515",

    fg="lime"

)

risk_label.pack(
    side="left",
    padx=20
)

file_label = tk.Label(

    stats_frame,

    text="File: None",

    font=("Arial", 11),

    bg="#151515",

    fg="white"

)

file_label.pack(
    side="left",
    padx=20
)

# ============================================
# BUTTON FRAME
# ============================================

button_frame = tk.Frame(
    root,
    bg="#101010"
)

button_frame.pack(
    pady=10
)

buttons = [

    ("🔍 Scan File",
     scan_file,
     "#008866"),

    ("📁 Scan Folder",
     scan_folder,
     "#222222"),

    ("📄 Save PDF",
     save_pdf,
     "#AA2222"),

    ("🗑 Clear Output",
     clear_output,
     "#004488")

]

for i, (text, cmd, color) in enumerate(buttons):

    btn = tk.Button(

        button_frame,

        text=text,

        command=cmd,

        width=18,

        height=2,

        bg=color,

        fg="white",

        font=(
            "Arial",
            10,
            "bold"
        )

    )

    btn.grid(
        row=0,
        column=i,
        padx=10
    )

# ============================================
# PROGRESS BAR
# ============================================

progress = ttk.Progressbar(

    root,

    mode='indeterminate',

    length=500

)

progress.pack(
    pady=5
)

# ============================================
# OUTPUT FRAME
# ============================================

output_frame = tk.Frame(
    root
)

output_frame.pack(

    fill="both",

    expand=True,

    padx=10,

    pady=10

)

# ============================================
# SCROLLBAR
# ============================================

scrollbar = tk.Scrollbar(
    output_frame
)

scrollbar.pack(
    side="right",
    fill="y"
)

# ============================================
# OUTPUT BOX
# ============================================

output = tk.Text(

    output_frame,

    wrap="word",

    font=("Consolas", 10),

    bg="black",

    fg="lime",

    yscrollcommand=scrollbar.set

)

output.pack(
    fill="both",
    expand=True
)

scrollbar.config(
    command=output.yview
)

# ============================================
# COLOR TAGS
# ============================================

output.tag_config(
    "danger",
    foreground="red"
)

output.tag_config(
    "warning",
    foreground="orange"
)

output.tag_config(
    "success",
    foreground="#00FF99"
)

output.tag_config(
    "normal",
    foreground="lime"
)

# ============================================
# STATUS BAR
# ============================================

status_label = tk.Label(

    root,

    text="Status: Ready",

    anchor="w",

    bg="#202020",

    fg="white"

)

status_label.pack(
    fill="x",
    side="bottom"
)

# ============================================
# START GUI
# ============================================

root.mainloop()